name: Auto Tag & Publish NuGet Package on Release Branch Merge

on:
  push:
    branches:
      - main  # Trigger when code is pushed or merged into main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history and tags

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x  # Adjust if necessary

      - name: Get previous branch name from commit message
        id: get_version
        run: |
          echo "Detecting merged branch..."
          MERGED_BRANCH=$(git log -1 --pretty=%B | grep -oE 'release/[0-9]+\.[0-9]+\.[0-9]+')
          echo "Merged branch: $MERGED_BRANCH"
          VERSION=${MERGED_BRANCH#release/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Extracted version: $VERSION"

      - name: Update version in .csproj
        run: |
          echo "Updating version in .csproj to $VERSION"
          sed -i "s|<Version>.*</Version>|<Version>${VERSION}</Version>|" *.csproj

      - name: Commit version bump and create tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "chore(release): v$VERSION [skip ci]" || echo "No changes to commit"
          git tag v$VERSION
          git push origin main --tags

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      - name: Pack NuGet package
        run: dotnet pack --configuration Release --output nupkg --no-build /p:PackageVersion=${{ env.VERSION }}

      - name: Publish to GitHub Packages
        run: dotnet nuget push nup
